"""Add tenancy id as foreign key in the company model

Revision ID: 9303cc47623d
Revises: 971a3d8172ee
Create Date: 2024-06-26 07:24:25.478312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9303cc47623d'
down_revision: Union[str, None] = '971a3d8172ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('tenancy_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'companies', 'tenancy', ['tenancy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'tenancy_id')
    # ### end Alembic commands ###
