"""Add meeting

Revision ID: 971a3d8172ee
Revises: 
Create Date: 2024-06-23 18:08:09.429061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '971a3d8172ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('third_party_participants', sa.Column('meeting_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'third_party_participants', 'meetings', ['meeting_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'third_party_participants', type_='foreignkey')
    op.drop_column('third_party_participants', 'meeting_id')
    # ### end Alembic commands ###
